fix and renaming moveSamplesheets to moveAndCheckSamplesheets + updated config files
molgenis/NGS_Automated pull request #249
Opened 2023-02-25 07:24 UTC by RoanKanninga

2023-02-25 07:42 UTC, RoanKanninga commented
Done testing. Can be merged

2023-03-07 09:38 UTC, pneerincx commented on bin/copyRawDataToTmp.sh
> +				rsync -rlDvc --relative --rsync-path="sudo -u ${group}-ateambot rsync" "/groups/${group}/${prm}/./rawdata/ngs/${line}"* "${DESTINATION_DIAGNOSTICS_CLUSTER}:${TMP_ROOT_DIR}/" \
Why is `t` to preserve time stamps dropped from the `rsync` command?

2023-03-07 09:48 UTC, pneerincx commented on bin/copyRawDataToTmp.sh
> +			if [[ -f "/groups/${group}/${prm}/rawdata/ngs/${line}" && "${copied}" == "no" ]]
- The `-f` test will only work for files and hence fail if we want to transfer a dir or symlink in the future. Why not test for whether the path exists. E.g. 
   ```
   if [[ -e "/groups/${group}/${prm}/rawdata/ngs/${line}" && "${copied}" == "no" ]]
   ```
- If `${line}` would also contain `rawdata/ngs` then this script could also work for other pipelines like the ones for processing array data. Now `rawdata/ngs/` is hard coded in front of the `${line}`making it only work for one type of data.

2023-03-07 09:54 UTC, pneerincx commented on bin/copyRawDataToTmp.sh
> +			exit 1
`exit 1` betekent dat het script eruit klapt. Aangezien deze functie wordt aangeroepen in een loop ```for sampleSheet in "${sampleSheetsFolder[@]}"``` worden eventuele volgende samplesheets niet meer verwerkt. Kortom een fout voor één samplesheet, maakt dat de verwerking van de rest stokt. Dat lijkt me niet de bedoeling. Er moet een "*.failed" gemaakt worden om de signaleren via `notifications.sh` dat het mis is gegaan met deze samplesheet, maar daarna moet dit script wel doorgaan en de rest verwerken.

2023-03-07 10:23 UTC, pneerincx commented on bin/moveAndCheckSamplesheets.sh
> +	Script to check samplesheets and move to another location potentially on another server.
```suggestion
Script to check samplesheets and move to another location potentially on another server.
```

2023-03-07 10:31 UTC, pneerincx commented on bin/moveAndCheckSamplesheets.sh
> +		log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "This is a GAP samplesheet, there is no samplesheetCheck at this moment"
```suggestion
		log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "This is a GAP samplesheet. There is no samplesheetCheck at this moment."
```

2023-03-07 10:32 UTC, pneerincx commented on bin/moveAndCheckSamplesheets.sh
> +		log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "This is a NGS samplesheet, lets check if the samplesheet is correct"
```suggestion
		log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "This is a NGS samplesheet. Lets check if the samplesheet is correct."
```

2023-03-07 10:33 UTC, pneerincx commented on bin/moveAndCheckSamplesheets.sh
> +			log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "samplesheet is correct"
```suggestion
			log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "Samplesheet ${samplesheet}.converted is correct."
```

2023-03-07 10:34 UTC, pneerincx commented on bin/moveAndCheckSamplesheets.sh
> +			log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "samplesheet is not correct"
```suggestion
			log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "Samplesheet ${samplesheet}.converted is not correct."
```

2023-03-07 10:38 UTC, pneerincx commented on bin/moveAndCheckSamplesheets.sh
> +			log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "Samplesheet is correct, continue"
This looks redundant as you already concluded based on only the exit status of ```if checkSampleSheet.py ...``` whether the samplesheet was correct or not.

2023-03-07 10:43 UTC, pneerincx commented on bin/moveAndCheckSamplesheets.sh
> +		log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "the samplesheet is a project samplesheet (no NGS_Demultiplexing), samplesheet moved to ${firstStepOfPipeline}"
```suggestion
		log4Bash 'INFO' "${LINENO}" "${FUNCNAME:-main}" '0' "The samplesheet is a project samplesheet (no NGS_Demultiplexing); firstStepOfPipeline was set to ${firstStepOfPipeline}."
```
Note that I do not this moving of the samplesheet

2023-03-07 10:54 UTC, pneerincx commented
General comment for `moveAndCheckSamplesheets.sh`: all logic is in a `main` with variables that have global scope. That can de dangerous and provide unexpected results. Our scripts usually try to keep the main code and list of global variables as short as possible: just a loop over whatever needs to be processed and for each item that needs to be processed a function is called. That function can then use `local` to declare variables which are only valid within the scope of that function and hence only valid for a specific item of the loop. By convention the names of these local variables start with an underscore. Currently there are global variables whose names start with underscores: they were probably copied from a function to the main of this script.

2023-03-07 11:04 UTC, pneerincx requested changes
See various comments.

2023-04-06 10:13 UTC, kdelange approved these changes

2023-04-06 10:18 UTC, merged