fixing cleanupDataOnTmp
molgenis/NGS_Automated pull request #291
Opened 2023-10-06 13:56 UTC by RoanKanninga

2023-10-09 09:42 UTC, pneerincx commented on bin/cleanupDataOnTmp.sh
>  			if [[ $(((dateInSecNow - dateInSecAnalysisData) / 86400)) -gt 10 ]]
Die 10 dagen is nu in meerdere regels hard coded. Ik zou daar een variabele van maken, want als het later een keer aangepast moet zorden zul je anders zien dat het ergens vergeten wordt en dan wordt het verwarrend.

2023-10-09 09:43 UTC, pneerincx commented on bin/cleanupDataOnTmp.sh
>  				log4Bash 'TRACE' "${LINENO}" "${FUNCNAME:-main}" '0' " the projectDataCopiedToPrm.finished is $(((dateInSecNow - dateInSecAnalysisData) / 86400)) day(s) old. To remove the project,tmp and generat
```suggestion
				log4Bash 'TRACE' "${LINENO}" "${FUNCNAME:-main}" '0' "The projectDataCopiedToPrm.finished is $(((dateInSecNow - dateInSecAnalysisData) / 86400)) day(s) old. To remove the project, tmp and generatedscripts folders the ${TMP_ROOT_DIR}/logs/${projectName}/run01.projectDataCopiedToPrm.finished file needs to be at least 10 days old."
```

2023-10-09 09:45 UTC, pneerincx commented on bin/cleanupDataOnTmp.sh
> +				rm -fv "${TMP_ROOT_DIR}/"{projects,tmp,generatedscripts}"/${pipeline}/${projectName}/"
Dit is een map, dus er moet `-R` bij lijkt me.

2023-10-09 09:45 UTC, pneerincx commented on bin/cleanupDataOnTmp.sh
> +				rm -fv "${TMP_ROOT_DIR}/rawdata/ngs/${runName}"
Dit is ook een map, dus er moet `-R` bij om recursief op te ruimen...

2023-10-09 09:46 UTC, pneerincx requested changes
See inline comments.

2023-10-11 12:13 UTC, kdelange approved these changes

2023-10-11 12:15 UTC, merged